#!/bin/bash

# Terminal colors for better visibility
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${GREEN}🚀 Starting MongoDB Infrastructure Deployment...${NC}"

# 1. Provision the Kubernetes Cluster using RKE
echo -e "${GREEN}1/4: Provisioning RKE Cluster...${NC}"
if rke up --config cluster.yml; then
    echo -e "${GREEN}✔ Cluster is up!${NC}"
else
    echo -e "${RED}✘ RKE provisioning failed.${NC}"
    exit 1
fi

# 2. Configure Persistent Storage (NFS)
# Applying StorageClass and PersistentVolumes for the ReplicaSet
echo -e "${GREEN}2/4: Setting up NFS Storage...${NC}"
kubectl apply -f nfs-storageclass.yaml
kubectl apply -f nfs-pvs-replicaset.yaml

# 3. Apply Kubernetes Secrets
# Injecting sensitive data (passwords, keys) into the cluster
echo -e "${GREEN}3/4: Applying MongoDB Secrets...${NC}"
kubectl apply -f secrets.yaml

# 4. Deploy MongoDB via Helm
# Installing/Upgrading the MongoDB ReplicaSet using Bitnami Chart
echo -e "${GREEN}4/4: Deploying MongoDB ReplicaSet via Helm...${NC}"
helm upgrade --install my-mongo bitnami/mongodb -f mongo-values.yaml

echo -e "${GREEN}-------------------------------------------------#!/bin/bash

# Terminal colors for better visibility
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${GREEN}🚀 Starting MongoDB Infrastructure Deployment...${NC}"

# 1. Provision the Kubernetes Cluster using RKE
# Updated path: added rke/ folder
echo -e "${GREEN}1/4: Provisioning RKE Cluster...${NC}"
if rke up --config rke/cluster.yml; then
    echo -e "${GREEN}✔ Cluster is up!${NC}"
else
    echo -e "${RED}✘ RKE provisioning failed.${NC}"
    exit 1
fi

# Set KUBECONFIG to the one generated by RKE (optional but helpful)
export KUBECONFIG="rke/kube_config_cluster.yml"

# 2. Configure Persistent Storage (NFS)
# Updated path: added k8s/storage/ folder
echo -e "${GREEN}2/4: Setting up NFS Storage...${NC}"
kubectl apply -f k8s/storage/nfs-storageclass.yaml
kubectl apply -f k8s/storage/nfs-pvs-replicaset.yaml

# 3. Apply Kubernetes Secrets
# Updated path: added k8s/mongodb/ folder
echo -e "${GREEN}3/4: Applying MongoDB Secrets...${NC}"
kubectl apply -f k8s/mongodb/secrets.yaml

# 4. Deploy MongoDB via Helm
# Updated path: added k8s/mongodb/ folder for the values file
echo -e "${GREEN}4/4: Deploying MongoDB ReplicaSet via Helm...${NC}"
helm upgrade --install my-mongo bitnami/mongodb -f k8s/mongodb/mongo-values.yaml

echo -e "${GREEN}--------------------------------------------------${NC}"
echo -e "${GREEN}✅ Deployment Finished Successfully!${NC}"
echo -e "${GREEN}Available NodePorts: 30017, 30018, 30019${NC}"
echo -e "${GREEN}Check status with: kubectl get pods -l app.kubernetes.io/name=mongodb${NC}"
echo -e "${GREEN}--------------------------------------------------${NC}"-${NC}"
echo -e "${GREEN}✅ Deployment Finished Successfully!${NC}"
echo -e "${GREEN}Available NodePorts: 30017, 30018, 30019${NC}"
echo -e "${GREEN}Check status with: kubectl get pods -l app.kubernetes.io/name=mongodb${NC}"
echo -e "${GREEN}--------------------------------------------------${NC}"